### PR TITLE
new picons, thx @DVB Man

### PR DESCRIPTION
**Pull request by unityhd**
Upload new picons, thx @DVB Man:
https://www.opena.tv/plugins/4023-piconsupdater-post416003.html#post416003

### CODE REVIEW

**Comment by arn354** [comment]
Conflicting files
picon_all/sky-krimi-hd.png

could you remove that change, so that i can merge it?
Sorry for delay

**Comment by unityhd** [comment]
I fixed it, should work fine now.
Have you already received a pull request from the new files in the forum?

**Comment by arn354** [comment]
there were 2 other PR's but not sure

**Comment by unityhd** [comment]
If you want i can upload the missing ones from the forum

**Comment by arn354** [comment]
i added you - so you are able now to directly push to this repository
Thanks for support :)

**Comment by unityhd** [comment]
Great thank you, so I can upload new stuff faster

**Pull request merged**
